---
- name: Configure web server
  hosts: web_servers
  become: true
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Deploy index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Welcome to Apache on Ubuntu</h1>"
